### PR TITLE
Remove restart and close everywhere

### PR DESCRIPTION
**Pull request by agger-magenta**

### CODE REVIEW

**Comment by magenta-af** [comment]
Perhaps I misunderstand something, but it looks like using this version of the script reintroduces Redmine bug 25950. Shouldn't we update `admin_scripts/dconf_policy_shutdown.sh` with the new `dconf` property name, and delete the `admin_scripts/ubuntu/ubuntu_16.04/layout/remove_shutdown_item.sh` script altogether?

(Also, this still doesn't prevent the user from doing `systemctl poweroff`; one of us should really learn how `polkit` works one of these days... :-)

**Comment by agger-magenta** [comment]
Alec, that is very possible. The line I introduced in this script made the "shutdown" icon go away in the greeter, i.e. for the `lightdm` user which was what the bug report complained about.

Regarding `systemctl poweroff` I thought that required root privileges. Hmm, apparently not. I think examining `polkit` is a very good idea.

**Comment by agger-magenta** [comment]
But it should be noted that Solrød was already using the script nearly as-is here, with the exceptions of the two lines I changed.

**Comment by magenta-af** [comment]
Yeah, it's confusing, isn't it? `shutdown` requires root privileges, but `systemctl poweroff` doesn't... Instead, it uses `polkit` to make a policy decision, and the default policy says "users with physical access to the computer can always pull the cable out, so let them shut the machine down cleanly as well".

We should find out how to implement a different policy for OS2borgerPC machines -- I think there's a simple key-value text file format for configuring these things.

**Comment by agger-magenta** [comment]
Another thing is: This pull request fixes what the customer perceived as a bug, namely that the shutdown icon appeared in the LightDM UI.  In that way, the changes corresponds to what is currently in production and to what the customer's bug report adressed.

The larger problem of users being able to do e.g. `systemctl poweroff` can and should be adressed in `polkit`, but maybe that's another task.  I think it would be good to merge this to document what is currently in production.

**Comment by magenta-af** [comment]
I don't disagree with the solution (i.e., setting a different `dconf` property than we presently do), and I don't mean to say that we should reimplement all of this using `polkit` immediately, but using this script as written reintroduces an old bug and relies on unsupported behaviour (https://lists.freedesktop.org/archives/dbus/2017-March/017110.html). `admin_scripts/dconf_policy_shutdown.sh` doesn't have either of these problems; is there something stopping us from making this change to that script?

**Comment by agger-magenta** [comment]
To my knowledge, there is nothing preventing us from using the `dconf_policy_shutdown` script - except for the fact that that script is not what the customer was using and in fact I had no idea that it existed. :) 

The `remove_shutdown_item` script appears to be what the customer has been using all the time and I didn't know it was deprecated.

**Comment by agger-magenta** [comment]
But then, if I understand you correctly, the correct solution is to delete the `remove_shutdown_item` & on the server replace it with the `dconf_policy_shutdown` script.

The only real hurdle to that is that we should code it and test it once again and probably also ask the customer to approve it once more.

However, I think it is a good idea to delete deprecated and bug-containing scripts and also remove them from the production server

**Comment by magenta-af** [comment]
> But then, if I understand you correctly, the correct solution is to delete the `remove_shutdown_item` & on the server replace it with the `dconf_policy_shutdown` script.

:+1:

> The only real hurdle to that is that we should code it and test it once again and probably also ask the customer to approve it once more.
> 
> However, I think it is a good idea to delete deprecated and bug-containing scripts and also remove them from the production server

Yeah, I agree... that's probably another branch for another day, though.

Would you mind also fixing this in `dconf_policy_shutdown.sh` as part of this branch? Then I'd have no problems accepting it. (While we have two scripts, they might as well both be correct...)

**Comment by agger-magenta** [comment]
:+1:

**Comment by dals83** [comment]
@agger-magenta is this branch ready to be merged? I mean has the dconf_policy_shutdown.sh script been changed according to @magenta-af suggestion?

**Comment by agger-magenta** [comment]
Alec has made some changes in another PR. I haven't had time to look at this the last week or so, so I don't know off my head if something needs to be added here.

**Comment by magenta-af** [comment]
I no longer know what to do with this PR. :-)

Now that #20 has been merged, we have a script that simply _forbids_ the user from shutting the system down. It doesn't just hide the menu options, it switches off the functionality (which, in turn, automatically hides the menu options).

... but now we have at least _three_ scripts that operate in this area:

* two `dconf`-powered scripts:-
  * `admin_scripts/ubuntu/ubuntu_16.04/layout/remove_shutdown_item.sh`, which is updated by this PR, and which is in use in production, but which relies on unsupported `dconf` behaviour; and
  * `admin_scripts/dconf_policy_shutdown.sh`, which isn't updated by this PR (and probably(?) isn't widely used in production) but uses `dconf` in a supported and reversible way; and
* one `polkit`-powered script, `admin_scripts/polkit_policy_shutdown.sh`, which hasn't been tested in production but which actually solves the underlying problem.

So I have no idea what to do now. In principle, we should probably delete the two `dconf` scripts altogether and migrate customers over to `polkit_policy_shutdown.sh`, but that's totally out of scope for this PR...

For now, though, I repeat that I would be happy to accept this PR if it also updated `admin_scripts/dconf_policy_shutdown.sh` with these new `dconf` properties -- while we have these two scripts, I see no reason why they should be allowed to drift out of sync.

**Comment by agger-magenta** [comment]
One solution, if you ask me, could be to replace the first `dconf`-based script with the new `polkit`-based one in the admin system and remove the second `dconf`-based system. Basically, this would mean deleting both `dconf`-based scripts from the repo and publishing the `polkit`-based one under the current name of the "wrong" `dconf` script.

Then we would have only one script left, the one with the most correct solution.

**Comment by agger-magenta** [comment]
`dconf` manipulations use `polkit` in our Ubuntu 20.04 version and henceforth.

**Pull request closed without merging**
