### PR TITLE
[41533] Add new script for adding network printer in Ubuntu 20.04

### PR DESCRIPTION
**Pull request by agger-magenta**

### CODE REVIEW

**Review by magenta-af — COMMENTED** [review]
We've had a customer request for the other printer management scripts as well (delete printer, set default printer, and list installed printers). Might it make sense to include those in this PR?

**Comment by agger-magenta** [comment]
Yes, they should be unproblematic.
This one is more tricky - there should be no problem at all, but I'm currently waiting for a customer to tell me whether this one actually manages to get paper out with print on it.

**Comment by magenta-af** [comment]
Hm. It occurs to me that we have a network printer here at home -- do you want me to give the script a trial run?

**Comment by agger-magenta** [comment]
Yes, feel free! The way it's working is with a PPD, which is supposedly soon to be deprecated, but I think it should work.

**Comment by agger-magenta** [comment]
So yes, it would be great if you'd try. This script is currently a local script for the customer working on it, but once we know it works we can make it a global script.

**Comment by magenta-af** [comment]
Argh, it turns out that -- although our network printer supports every driverless access protocol known to man (Google Cloud Print, a web form, IPP, `lpd` and PDL, whatever _that_ is) -- it doesn't actually have a PPD, so I can't try it out with the script! Sorry...

**Comment by agger-magenta** [comment]
We'll wait for the customer instead, I'll call them next week and hear.

**Comment by agger-magenta** [comment]
The customer has approved the add printer script, it works! Ready for re-review.

**Pull request merged**
